version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PG_PORT=5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_LOCAL_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: nestjs-docker
    build:
      context: ./
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${API_LOCAL_PORT:-3000}:${API_PORT:-3000}"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_PORT=${API_PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
